"""initial schema

Revision ID: 48d048a4819d
Revises: 
Create Date: 2026-09-07 11:53:55.780184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '48d048a4819d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adsb_query_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tile', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('queried_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tile', 'date', name='uq_adsb_query_cache_tile_date')
    )
    op.create_table('chip_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tile', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('col', sa.Float(), nullable=False),
    sa.Column('row', sa.Float(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path', name='uq_chip_cache_file_path')
    )
    op.create_index('ix_chip_cache_tile_date', 'chip_cache', ['tile', 'date'], unique=False)
    op.create_geospatial_table('pipeline_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aoi_name', sa.String(), nullable=True),
    sa.Column('aoi_geom', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('lon_min', sa.Float(), nullable=True),
    sa.Column('lon_max', sa.Float(), nullable=True),
    sa.Column('lat_min', sa.Float(), nullable=True),
    sa.Column('lat_max', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('tile_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_pipeline_run_aoi_geom', 'pipeline_run', ['aoi_geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('tile_scan_params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tile', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('t_top', sa.DateTime(timezone=True), nullable=False),
    sa.Column('t_bottom', sa.DateTime(timezone=True), nullable=False),
    sa.Column('t_query_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('t_query_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('west', sa.Float(), nullable=False),
    sa.Column('east', sa.Float(), nullable=False),
    sa.Column('south', sa.Float(), nullable=False),
    sa.Column('north', sa.Float(), nullable=False),
    sa.Column('cloud_pct', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tile', 'date', name='uq_tile_scan_params_tile_date')
    )
    op.create_table('mask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('tile', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('epsg', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('candidate_pixel_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'image_id', name='uq_mask_run_image')
    )
    op.create_index(op.f('ix_mask_run_id'), 'mask', ['run_id'], unique=False)
    op.create_table('metrics_by_background',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('background_type', sa.SmallInteger(), nullable=False),
    sa.Column('background_label', sa.String(), nullable=False),
    sa.Column('tp', sa.Integer(), nullable=False),
    sa.Column('fp', sa.Integer(), nullable=False),
    sa.Column('fn', sa.Integer(), nullable=False),
    sa.Column('tp1', sa.Integer(), nullable=False),
    sa.Column('n_adsb_total', sa.Integer(), nullable=False),
    sa.Column('n_adsb_visible', sa.Integer(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1', sa.Float(), nullable=True),
    sa.Column('fpr', sa.Float(), nullable=True),
    sa.Column('fnr', sa.Float(), nullable=True),
    sa.Column('detectable_fraction', sa.Float(), nullable=True),
    sa.Column('tp1_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_by_background_run_id'), 'metrics_by_background', ['run_id'], unique=False)
    op.create_table('metrics_by_scene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('tile', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('cloud_pct', sa.Float(), nullable=True),
    sa.Column('modal_background', sa.SmallInteger(), nullable=True),
    sa.Column('tp', sa.Integer(), nullable=False),
    sa.Column('fp', sa.Integer(), nullable=False),
    sa.Column('fn', sa.Integer(), nullable=False),
    sa.Column('tp1', sa.Integer(), nullable=False),
    sa.Column('n_adsb_total', sa.Integer(), nullable=False),
    sa.Column('n_adsb_visible', sa.Integer(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1', sa.Float(), nullable=True),
    sa.Column('fpr', sa.Float(), nullable=True),
    sa.Column('fnr', sa.Float(), nullable=True),
    sa.Column('detectable_fraction', sa.Float(), nullable=True),
    sa.Column('tp1_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_by_scene_run_id'), 'metrics_by_scene', ['run_id'], unique=False)
    op.create_geospatial_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('mask_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('tile', sa.String(), nullable=False),
    sa.Column('col', sa.Float(), nullable=False),
    sa.Column('row', sa.Float(), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('epsg', sa.Integer(), nullable=False),
    sa.Column('cluster_excluded', sa.Boolean(), nullable=False),
    sa.Column('road_excluded', sa.Boolean(), nullable=False),
    sa.Column('road_score', sa.Float(), nullable=True),
    sa.Column('seam_excluded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mask_id'], ['mask.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'image_id', 'col', 'row', name='uq_candidate_run_image_col_row')
    )
    op.create_geospatial_index('idx_candidate_geom', 'candidate', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_candidate_run_id'), 'candidate', ['run_id'], unique=False)
    op.create_index('ix_candidate_run_image', 'candidate', ['run_id', 'image_id'], unique=False)
    op.create_table('chip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id')
    )
    op.create_index(op.f('ix_chip_run_id'), 'chip', ['run_id'], unique=False)
    op.create_table('collinearity_triplet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('c_b2_col', sa.Float(), nullable=True),
    sa.Column('c_b2_row', sa.Float(), nullable=True),
    sa.Column('c_b2_area', sa.Float(), nullable=True),
    sa.Column('c_b3_col', sa.Float(), nullable=True),
    sa.Column('c_b3_row', sa.Float(), nullable=True),
    sa.Column('c_b3_area', sa.Float(), nullable=True),
    sa.Column('c_b4_col', sa.Float(), nullable=True),
    sa.Column('c_b4_row', sa.Float(), nullable=True),
    sa.Column('c_b4_area', sa.Float(), nullable=True),
    sa.Column('angle_deg', sa.Float(), nullable=True),
    sa.Column('colinear_found', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collinearity_triplet_candidate_id'), 'collinearity_triplet', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_collinearity_triplet_run_id'), 'collinearity_triplet', ['run_id'], unique=False)
    op.create_table('confirmed_detection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('d_band2_3_m', sa.Float(), nullable=True),
    sa.Column('d_band3_4_m', sa.Float(), nullable=True),
    sa.Column('residual_m', sa.Float(), nullable=True),
    sa.Column('angle_deg', sa.Float(), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('c_b2_col', sa.Float(), nullable=True),
    sa.Column('c_b2_row', sa.Float(), nullable=True),
    sa.Column('c_b3_col', sa.Float(), nullable=True),
    sa.Column('c_b3_row', sa.Float(), nullable=True),
    sa.Column('c_b4_col', sa.Float(), nullable=True),
    sa.Column('c_b4_row', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id')
    )
    op.create_index(op.f('ix_confirmed_detection_run_id'), 'confirmed_detection', ['run_id'], unique=False)
    op.create_geospatial_table('evaluation_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('in_pipeline', sa.Boolean(), nullable=False),
    sa.Column('in_adsb', sa.Boolean(), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('match_distance_m', sa.Float(), nullable=True),
    sa.Column('matched_icao24', sa.String(), nullable=True),
    sa.Column('matched_callsign', sa.String(), nullable=True),
    sa.Column('icao24', sa.String(), nullable=True),
    sa.Column('callsign', sa.String(), nullable=True),
    sa.Column('baroaltitude', sa.Float(), nullable=True),
    sa.Column('geoaltitude', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('angle_deg', sa.Float(), nullable=True),
    sa.Column('residual_m', sa.Float(), nullable=True),
    sa.Column('outside_bounds', sa.Boolean(), nullable=False),
    sa.Column('inspected', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('is_flying', sa.Boolean(), nullable=True),
    sa.Column('seamline_duplicate', sa.Boolean(), nullable=True),
    sa.Column('near_bounds', sa.Boolean(), nullable=True),
    sa.Column('background_type', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('note_code', sa.String(), nullable=True),
    sa.Column('cloud_pct', sa.Float(), nullable=True),
    sa.Column('annotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_evaluation_point_geom', 'evaluation_point', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_evaluation_point_run_id'), 'evaluation_point', ['run_id'], unique=False)
    op.create_index('ix_evaluation_point_run_image', 'evaluation_point', ['run_id', 'image_id'], unique=False)
    op.create_table('reflectance_centroid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('band', sa.String(), nullable=False),
    sa.Column('col', sa.Float(), nullable=False),
    sa.Column('row', sa.Float(), nullable=False),
    sa.Column('area', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reflectance_centroid_candidate_id'), 'reflectance_centroid', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_reflectance_centroid_run_id'), 'reflectance_centroid', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reflectance_centroid_run_id'), table_name='reflectance_centroid')
    op.drop_index(op.f('ix_reflectance_centroid_candidate_id'), table_name='reflectance_centroid')
    op.drop_table('reflectance_centroid')
    op.drop_index('ix_evaluation_point_run_image', table_name='evaluation_point')
    op.drop_index(op.f('ix_evaluation_point_run_id'), table_name='evaluation_point')
    op.drop_geospatial_index('idx_evaluation_point_geom', table_name='evaluation_point', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('evaluation_point')
    op.drop_index(op.f('ix_confirmed_detection_run_id'), table_name='confirmed_detection')
    op.drop_table('confirmed_detection')
    op.drop_index(op.f('ix_collinearity_triplet_run_id'), table_name='collinearity_triplet')
    op.drop_index(op.f('ix_collinearity_triplet_candidate_id'), table_name='collinearity_triplet')
    op.drop_table('collinearity_triplet')
    op.drop_index(op.f('ix_chip_run_id'), table_name='chip')
    op.drop_table('chip')
    op.drop_index('ix_candidate_run_image', table_name='candidate')
    op.drop_index(op.f('ix_candidate_run_id'), table_name='candidate')
    op.drop_geospatial_index('idx_candidate_geom', table_name='candidate', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('candidate')
    op.drop_index(op.f('ix_metrics_by_scene_run_id'), table_name='metrics_by_scene')
    op.drop_table('metrics_by_scene')
    op.drop_index(op.f('ix_metrics_by_background_run_id'), table_name='metrics_by_background')
    op.drop_table('metrics_by_background')
    op.drop_index(op.f('ix_mask_run_id'), table_name='mask')
    op.drop_table('mask')
    op.drop_table('tile_scan_params')
    op.drop_geospatial_index('idx_pipeline_run_aoi_geom', table_name='pipeline_run', postgresql_using='gist', column_name='aoi_geom')
    op.drop_geospatial_table('pipeline_run')
    op.drop_index('ix_chip_cache_tile_date', table_name='chip_cache')
    op.drop_table('chip_cache')
    op.drop_table('adsb_query_cache')
    # ### end Alembic commands ###
